### PR TITLE
Add the ability to set a custom configuration provider

### PR DESCRIPTION
**Pull request by merlindorin**

### CODE REVIEW

**Comment by lorenzoferrarajr** [comment]
Hi @iam-merlin 

Thank you for the pull request, I think you had a good idea. Please give me a couple of days to try it out before merging.

**Comment by iam-merlin** [comment]
Hi, thank you! you'r welcome. 
I already use it (not in prod) and it works fine. It's a basic stuff, that could be rounded off later with adapter but... it would require more work and might not be necessary.

**Comment by lorenzoferrarajr** [comment]
Hi @iam-merlin,
I was wandering if you tried to resolve the problem of getting the options from the database creating a custom `lfjopauth_module_options`

Now `lfjopauth_module_options` is defined as a factory:

```php
'lfjopauth_module_options' => function ($sm) {
    $config = $sm->get('Config');
    return isset($config['lfjopauth']) ? $config['lfjopauth'] : array();
}
```

you could try do do some like:

```php
'lfjopauth_module_options' => function ($sm) {
    $optionsFromDb = $sm->get('entity_manager')->fetch(...);

    $config = $sm->get('Config');
    $optionsFromConfigFile = isset($config['lfjopauth']) ? $config['lfjopauth'] : array();

    return = array_merge_recursive($optionsFromConfigFile, array('Strategy' => $optionsFromDb));
}
```

Now, this is just pseudo-code. But it would be great if you could try it.

Thanks!

**Comment by iam-merlin** [comment]
Hi :)
Very good pseudo code, this is very closed of what I've done first (doctrine instead... different style, same taste ^^) and it works fine.

I actually used opauth as a token provider to integrate external service... not directly as an "authorization service" for my application but as a "service provider" instead.

This is an example of how I'm using this little improvement (closure cannot provide directly the context, that why I didn't use it) :

```PHP

class LfjopauthModuleOptions implements OptionsProviderInterface, ServiceLocatorAwareInterface
{

    use ServiceLocatorAwareTrait;

    /**
     * @return Array return the lfjopauth_module_options
     */
    public function getOptions($provider)
    {
        /** @var EntityManager $em */
        $em = $this->getServiceLocator()->get('Doctrine\ORM\EntityManager');
        $rp = $em->getRepository('EokoSecurity\Entity\ExtOauthProvider');

        /** @var ExtOauthProvider $oauthProvider */
        $oauthProvider = $rp->find($provider);

        $scopes = $oauthProvider->getExtOauthScopes()->map(
            function (ExtOauthScopes $scopes) {
                return $scopes->getScope();
            }
        )->toArray();

        return array(
            'security_salt' => 'Some random text',
            'Strategy' => array(
                $oauthProvider->getProviderName() => array(
                    'client_id' => $oauthProvider->getExtOauthClientsClient()->getClientId(),
                    'client_secret' => $oauthProvider->getExtOauthClientsClient()->getClientSecret(),
                    'access_type' => $oauthProvider->getExtOauthClientsClient()->getAccessType(),
                    'scope' => implode(' ', $scopes),
                    'strategy_class' => $oauthProvider->getExtOauthClientsClient()->getStrategyName(),
                    'strategy_url_name' => $oauthProvider->getProviderName()
                ),
            ),
            'check_controller_enabled' => false
        );
    }
}
```

**Comment by lorenzoferrarajr** [comment]
Ok, so your `LfjopauthModuleOptions` class is added to the service manager using the `lfjopauth_module_options` key?

**Comment by lorenzoferrarajr** [comment]
@iam-merlin your change is making me think about other changes that could make the code better. Are you available on irc.freenode?

**Comment by merlindorin** [comment]
@lorenzoferrarajr sorry for the late... thank you for the merge. I'll be back soon for more stuff ;)

**Pull request merged**
